### ISSUE TITLE
Not getting Cropped Image

### ISSUE THREAD

**Issue by mital87** [meim/MMScaner#3]
@meim: How can I get cropped image automatically or manually?

**Comment by meim** [comment]
You can switch to the feature/image_edit branch, and should be able to get the auto cropped image. 
Manually cropping is still under development @mital87

**Comment by mital87** [comment]
@meim: I have download source code from feature/image_edit branch. I am not able to capture document image automatically. Can you please help me how can I do automatically?

**Comment by meim** [comment]
Once you start the camera, put a piece of white paper on a high contrast background ( e.g dark backround ), and you will see the document area being highlighted on the camera view. Hold the phone and press the capture button at the bottom, you'll get the auto cropped image. @mital87

**Comment by mital87** [comment]
@meim: Thanks for the reply. Is there any way to capture Image without pressing the Capture button When the document is focussed?

**Comment by meim** [comment]
@mital87 It hasn't been implemented yet, but definitely can be added.

**Comment by mital87** [comment]
@meim: Thanks for the support. I am waiting for that feature in the existing library. Great Job...!!!

**Comment by meim** [comment]
@mital87 Will let you know once it's added :)

**Comment by mital87** [comment]
@meim: Ya sure.

**Comment by mital87** [comment]
@meim: Can we improve the object(document) recognition & quality of crop image?

**Comment by meim** [comment]
@mital87: At the moment, there's no plan for this. Because the object recognition is done by CoreImage, and the crop image has already got the highest possible resolution (although you may not notice that in the preview mode, but if you look at the actual image, the resolution is quite high).

**Comment by mital87** [comment]
@meim: Thanks for the reply. When will you provide us the auto capture feature (ie. capture Image without pressing the Capture button When the document is focussed)?

**Comment by meim** [comment]
@mital87: Hopefully within this month.

**Comment by mital87** [comment]
@meim: I have used your library in my project & It's working fine. I want to implement capture Image without pressing the Capture button When the document is focussed. Can you please assist me, How can I achieve this?

**Comment by mital87** [comment]
@meim: Can you please assist me?

**Comment by meim** [comment]
Still working on the solution of this feature. @mital87

**Comment by mital87** [comment]
@meim: Okay. Are you got any success on that?
